steps:
# - name: gcr.io/cloud-builders/gcloud
- name: 'bash'
  args:
    - '-c'
    - |
      if [[ "$_IF_TAG" == "T" ]]; then
          - name: python  
            args: ['python','quickstart-automate/main.py']

          - name: 'gcr.io/cloud-builders/docker'
            args: ['build', '-t', 'us-central1-docker.pkg.dev/carbide-bongo-339207/first-app/my-app:${TAG_NAME}', 'quickstart-automate']
          - name: 'gcr.io/cloud-builders/docker'
            args: ['push','us-central1-docker.pkg.dev/carbide-bongo-339207/first-app/my-app:${TAG_NAME}']
      fi
      
      if [[ "$_IF_TAG" == "F" ]]
        then
            name: python
            args: ['python','quickstart-automate/main.py']
      fi
