steps:
  - name: python
    # entrypoint: pip
    # args: ["install","-r","requirements.txt","--user"]
    args: ['python','quickstart-automate/main.py']
  - name: 'gcr.io/cloud-builders/docker'
    tag_id: v1.1
    args: ['build', '-t', 
         'us-central1-docker.pkg.dev/carbide-bongo-339207/first-app/my-app:${tag_id}', 'quickstart-automate']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'us-central1-docker.pkg.dev/carbide-bongo-339207/first-app/my-app:${tag_id}']
    

    