jobs:
#   - name: python
    # entrypoint: pip
    # args: ["install","-r","requirements.txt","--user"]
    
  #Unittesting
  # - name: python
  #   entrypoint: python
  #   args: ["-m", "pytest", "--junitxml=${SHORT_SHA}_test_log.xml"]
  rules:
    - if: '$_IF_TAG == "T"'
      - name: 'gcr.io/cloud-builders/docker'
        args: ['build', '-t', 
             'us-central1-docker.pkg.dev/carbide-bongo-339207/first-app/my-app:${TAG_NAME}', 'quickstart-automate']
      - name: 'gcr.io/cloud-builders/docker'
        args: ['push',
              'us-central1-docker.pkg.dev/carbide-bongo-339207/first-app/my-app:${TAG_NAME}']
    - if: '$_IF_TAG == "F"'
      - name: python
        args: ['python','quickstart-automate/main.py']


# substitutions: 
#   _TAG_ID: v1.0.2
# options:
#   substitution_option: 'ALLOW_LOOSE'
    

    
