variables:
- name: TAG_ID
  value: v1.1
steps:
  - name: python
    # entrypoint: pip
    # args: ["install","-r","requirements.txt","--user"]
    args: ['python','quickstart-automate/main.py']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
         'us-central1-docker.pkg.dev/carbide-bongo-339207/first-app/my-app:variables.TAG_ID', 'quickstart-automate']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'us-central1-docker.pkg.dev/carbide-bongo-339207/first-app/my-app:variables.TAG_ID']
    

    